name: rmpp-app
channels:
  - pytorch
  - radiomics
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas
  - scikit-learn
  - joblib
  - plotly
  - pydicom
  - SimpleITK
  - opencv
  - pytorch
  - torchvision
  - cpuonly
  - pyradiomics
  - xgboost
  - lightgbm
  - pip
  - pip:
      - streamlit