name: rmpp-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pip
  - pip:
      - streamlit
      - pandas
      - pydicom
      - opencv-python-headless
      - torch
      - torchvision
      - joblib
      - SimpleITK
      - pyradiomics
      - plotly
      - scikit-learn
      - xgboost
      - lightgbm