name: rmpp-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas
  - scikit-learn
  - joblib
  - plotly
  - pydicom
  - SimpleITK
  - opencv
  - pip
  - pip:
      - streamlit
      - torch
      - torchvision
      - pyradiomics
      - xgboost
      - lightgbm